import "../assets/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/header/header";

const suit = localFont({
  src: "../assets/fonts/SUIT.woff2",
  variable: "--font-suit",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Valley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${suit.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
